# all moves from first gen
attacks = [
    {'name': 'Absorb', 'category': 'Special', 'power': 20, 'accuracy': 100, 'pp': 20, 'type': 'Grass'}, 
    {'name': 'Acid', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 30, 'type': 'Poison'}, 
    {'name': 'Acid Armor', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Poison'}, 
    {'name': 'Agility', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Psychic'},
    {'name': 'Amnesia', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Psychic'},
    {'name': 'Aurora Beam', 'category': 'Special', 'power': 65, 'accuracy': 100, 'pp': 20, 'type': 'Ice'},
    {'name': 'Barrage', 'category': 'Physical', 'power': 15, 'accuracy': 85, 'pp': 20, 'type': 'Normal'},
    {'name': 'Barrier', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Psychic'},
    {'name': 'Bind', 'category': 'Physical', 'power': 15, 'accuracy': 75, 'pp': 20, 'type': 'Normal'},
    {'name': 'Bite', 'category': 'Physical', 'power': 60, 'accuracy': 100, 'pp': 25, 'type': 'Normal'},
    {'name': 'Blizzard', 'category': 'Special', 'power': 120, 'accuracy': 90, 'pp': 5, 'type': 'Ice'},
    {'name': 'Body Slam', 'category': 'Physical', 'power': 85, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'Bone Club', 'category': 'Physical', 'power': 65, 'accuracy': 85, 'pp': 20, 'type': 'Ground'},
    {'name': 'Bonemerang', 'category': 'Physical', 'power': 50, 'accuracy': 90, 'pp': 10, 'type': 'Ground'},
    {'name': 'Bubble', 'category': 'Special', 'power': 20, 'accuracy': 100, 'pp': 30, 'type': 'Water'},
    {'name': 'Bubble Beam', 'category': 'Special', 'power': 65, 'accuracy': 100, 'pp': 20, 'type': 'Water'},
    {'name': 'Clamp', 'category': 'Special', 'power': 35, 'accuracy': 75, 'pp': 10, 'type': 'Water'},
    {'name': 'Comet Punch', 'category': 'Physical', 'power': 18, 'accuracy': 85, 'pp': 15, 'type': 'Normal'},
    {'name': 'Confuse Ray', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 10, 'type': 'Ghost'},
    {'name': 'Confusion', 'category': 'Special', 'power': 50, 'accuracy': 100, 'pp': 25, 'type': 'Psychic'},
    {'name': 'Constrict', 'category': 'Physical', 'power': 10, 'accuracy': 100, 'pp': 35, 'type': 'Normal'},
    {'name': 'Conversion', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Normal'},
    {'name': 'Crabhammer', 'category': 'Special', 'power': 90, 'accuracy': 85, 'pp': 10, 'type': 'Water'},
    {'name': 'Cut', 'category': 'Physical', 'power': 50, 'accuracy': 95, 'pp': 30, 'type': 'Normal'},
    {'name': 'Defense Curl', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Normal'},
    {'name': 'Dig', 'category': 'Physical', 'power': 100, 'accuracy': 100, 'pp': 10, 'type': 'Ground'},
    {'name': 'Dizzy Punch', 'category': 'Physical', 'power': 70, 'accuracy': 100, 'pp': 10, 'type': 'Normal'},
    {'name': 'Double Kick', 'category': 'Physical', 'power': 30, 'accuracy': 100, 'pp': 30, 'type': 'Fighting'},
    {'name': 'Double Slap', 'category': 'Physical', 'power': 15, 'accuracy': 85, 'pp': 10, 'type': 'Normal'},
    {'name': 'Double Team', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 15, 'type': 'Normal'},
    {'name': 'Double-Edge', 'category': 'Physical', 'power': 100, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'Dragon Rage', 'category': 'Special', 'power': 0, 'accuracy': 100, 'pp': 10, 'type': 'Dragon'},
    {'name': 'Dream Eater', 'category': 'Special', 'power': 100, 'accuracy': 100, 'pp': 15, 'type': 'Psychic'},
    {'name': 'Drill Peck', 'category': 'Physical', 'power': 80, 'accuracy': 100, 'pp': 20, 'type': 'Flying'},
    {'name': 'Earthquake', 'category': 'Physical', 'power': 100, 'accuracy': 100, 'pp': 10, 'type': 'Ground'},
    {'name': 'Egg Bomb', 'category': 'Physical', 'power': 100, 'accuracy': 75, 'pp': 10, 'type': 'Normal'},
    {'name': 'Ember', 'category': 'Special', 'power': 40, 'accuracy': 100, 'pp': 25, 'type': 'Fire'},
    {'name': 'Explosion', 'category': 'Physical', 'power': 170, 'accuracy': 100, 'pp': 5, 'type': 'Normal'},
    {'name': 'Fire Blast', 'category': 'Special', 'power': 120, 'accuracy': 85, 'pp': 5, 'type': 'Fire'},
    {'name': 'Fire Punch', 'category': 'Special', 'power': 75, 'accuracy': 100, 'pp': 15, 'type': 'Fire'},
    {'name': 'Fire Spin', 'category': 'Special', 'power': 15, 'accuracy': 70, 'pp': 15, 'type': 'Fire'},
    {'name': 'Fissure', 'category': 'Physical', 'power': 0, 'accuracy': 30, 'pp': 5, 'type': 'Ground'},
    {'name': 'Flamethrower', 'category': 'Special', 'power': 95, 'accuracy': 100, 'pp': 15, 'type': 'Fire'},
    {'name': 'Flash', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 70, 'pp': 20, 'type': 'Normal'},
    {'name': 'Fly', 'category': 'Physical', 'power': 70, 'accuracy': 95, 'pp': 15, 'type': 'Flying'},
    {'name': 'Focus Energy', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Normal'},
    {'name': 'Fury Attack', 'category': 'Physical', 'power': 15, 'accuracy': 85, 'pp': 20, 'type': 'Normal'},
    {'name': 'Fury Swipes', 'category': 'Physical', 'power': 18, 'accuracy': 80, 'pp': 15, 'type': 'Normal'},
    {'name': 'Glare', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 75, 'pp': 30, 'type': 'Normal'},
    {'name': 'Growl', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 40, 'type': 'Normal'},
    {'name': 'Growth', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Normal'},
    {'name': 'Guillotine', 'category': 'Physical', 'power': 0, 'accuracy': 30, 'pp': 5, 'type': 'Normal'},
    {'name': 'Gust', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 35, 'type': 'Normal'},
    {'name': 'Harden', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Normal'},
    {'name': 'Haze', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Ice'},
    {'name': 'Headbutt', 'category': 'Physical', 'power': 70, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'High Jump Kick', 'category': 'Physical', 'power': 85, 'accuracy': 90, 'pp': 20, 'type': 'Fighting'},
    {'name': 'Horn Attack', 'category': 'Physical', 'power': 65, 'accuracy': 100, 'pp': 25, 'type': 'Normal'},
    {'name': 'Horn Drill', 'category': 'Physical', 'power': 0, 'accuracy': 30, 'pp': 5, 'type': 'Normal'},
    {'name': 'Hydro Pump', 'category': 'Special', 'power': 120, 'accuracy': 80, 'pp': 5, 'type': 'Water'},
    {'name': 'Hyper Beam', 'category': 'Physical', 'power': 150, 'accuracy': 90, 'pp': 5, 'type': 'Normal'},
    {'name': 'Hyper Fang', 'category': 'Physical', 'power': 80, 'accuracy': 90, 'pp': 15, 'type': 'Normal'},
    {'name': 'Hypnosis', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 60, 'pp': 20, 'type': 'Psychic'},
    {'name': 'Ice Beam', 'category': 'Special', 'power': 95, 'accuracy': 100, 'pp': 10, 'type': 'Ice'},
    {'name': 'Ice Punch', 'category': 'Special', 'power': 75, 'accuracy': 100, 'pp': 15, 'type': 'Ice'},
    {'name': 'Jump Kick', 'category': 'Physical', 'power': 70, 'accuracy': 95, 'pp': 25, 'type': 'Fighting'},
    {'name': 'Karate Chop', 'category': 'Physical', 'power': 50, 'accuracy': 100, 'pp': 25, 'type': 'Normal'},
    {'name': 'Kinesis', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 80, 'pp': 15, 'type': 'Psychic'},
    {'name': 'Leech Life', 'category': 'Physical', 'power': 20, 'accuracy': 100, 'pp': 15, 'type': 'Bug'},
    {'name': 'Leech Seed', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 90, 'pp': 10, 'type': 'Grass'},
    {'name': 'Leer', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 30, 'type': 'Normal'},
    {'name': 'Lick', 'category': 'Physical', 'power': 20, 'accuracy': 100, 'pp': 30, 'type': 'Ghost'},
    {'name': 'Light Screen', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Psychic'},
    {'name': 'Lovely Kiss', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 75, 'pp': 10, 'type': 'Normal'},
    {'name': 'Low Kick', 'category': 'Physical', 'power': 50, 'accuracy': 90, 'pp': 20, 'type': 'Fighting'},
    {'name': 'Meditate', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Psychic'},
    {'name': 'Mega Drain', 'category': 'Special', 'power': 40, 'accuracy': 100, 'pp': 10, 'type': 'Grass'},
    {'name': 'Mega Kick', 'category': 'Physical', 'power': 120, 'accuracy': 75, 'pp': 5, 'type': 'Normal'},
    {'name': 'Mega Punch', 'category': 'Physical', 'power': 80, 'accuracy': 85, 'pp': 20, 'type': 'Normal'},
    {'name': 'Metronome', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Mimic', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Minimize', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Normal'},
    {'name': 'Mirror Move', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Flying'},
    {'name': 'Mist', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Ice'},
    {'name': 'Night Shade', 'category': 'Physical', 'power': 0, 'accuracy': 100, 'pp': 15, 'type': 'Ghost'},
    {'name': 'Pay Day', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Peck', 'category': 'Physical', 'power': 35, 'accuracy': 100, 'pp': 35, 'type': 'Flying'},
    {'name': 'Petal Dance', 'category': 'Special', 'power': 70, 'accuracy': 100, 'pp': 20, 'type': 'Grass'},
    {'name': 'Pin Missile', 'category': 'Physical', 'power': 14, 'accuracy': 85, 'pp': 20, 'type': 'Bug'},
    {'name': 'Poison Gas', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 55, 'pp': 40, 'type': 'Poison'},
    {'name': 'Poison Powder', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 75, 'pp': 35, 'type': 'Poison'},
    {'name': 'Poison Sting', 'category': 'Physical', 'power': 15, 'accuracy': 100, 'pp': 35, 'type': 'Poison'},
    {'name': 'Pound', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 35, 'type': 'Normal'},
    {'name': 'Psybeam', 'category': 'Special', 'power': 65, 'accuracy': 100, 'pp': 20, 'type': 'Psychic'},
    {'name': 'Psychic', 'category': 'Special', 'power': 90, 'accuracy': 100, 'pp': 10, 'type': 'Psychic'},
    {'name': 'Psywave', 'category': 'Special', 'power': 0, 'accuracy': 80, 'pp': 15, 'type': 'Psychic'},
    {'name': 'Quick Attack', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 30, 'type': 'Normal'},
    {'name': 'Rage', 'category': 'Physical', 'power': 20, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Razor Leaf', 'category': 'Special', 'power': 55, 'accuracy': 95, 'pp': 25, 'type': 'Grass'},
    {'name': 'Razor Wind', 'category': 'Physical', 'power': 80, 'accuracy': 75, 'pp': 10, 'type': 'Normal'},
    {'name': 'Recover', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Normal'},
    {'name': 'Reflect', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Psychic'},
    {'name': 'Rest', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Psychic'},
    {'name': 'Roar', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Rock Slide', 'category': 'Physical', 'power': 75, 'accuracy': 90, 'pp': 10, 'type': 'Rock'},
    {'name': 'Rock Throw', 'category': 'Physical', 'power': 50, 'accuracy': 90, 'pp': 15, 'type': 'Rock'},
    {'name': 'Rolling Kick', 'category': 'Physical', 'power': 60, 'accuracy': 85, 'pp': 15, 'type': 'Fighting'},
    {'name': 'Sand Attack', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 15, 'type': 'Ground'},
    {'name': 'Scratch', 'category': 'Physical', 'power': 40, 'accuracy': 100, 'pp': 35, 'type': 'Normal'},
    {'name': 'Screech', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 85, 'pp': 40, 'type': 'Normal'},
    {'name': 'Seismic Toss', 'category': 'Physical', 'power': 0, 'accuracy': 100, 'pp': 20, 'type': 'Fighting'},
    {'name': 'Self-Destruct', 'category': 'Physical', 'power': 130, 'accuracy': 100, 'pp': 5, 'type': 'Normal'},
    {'name': 'Sharpen', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Normal'},
    {'name': 'Sing', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 55, 'pp': 15, 'type': 'Normal'},
    {'name': 'Skull Bash', 'category': 'Physical', 'power': 100, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'Sky Attack', 'category': 'Physical', 'power': 140, 'accuracy': 90, 'pp': 5, 'type': 'Flying'},
    {'name': 'Slam', 'category': 'Physical', 'power': 80, 'accuracy': 75, 'pp': 20, 'type': 'Normal'},
    {'name': 'Slash', 'category': 'Physical', 'power': 70, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Sleep Powder', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 75, 'pp': 15, 'type': 'Grass'},
    {'name': 'Sludge', 'category': 'Physical', 'power': 65, 'accuracy': 100, 'pp': 20, 'type': 'Poison'},
    {'name': 'Smog', 'category': 'Physical', 'power': 20, 'accuracy': 70, 'pp': 20, 'type': 'Poison'},
    {'name': 'Smokescreen', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Soft-Boiled', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Solar Beam', 'category': 'Special', 'power': 120, 'accuracy': 100, 'pp': 10, 'type': 'Grass'},
    {'name': 'Sonic Boom', 'category': 'Physical', 'power': 0, 'accuracy': 90, 'pp': 20, 'type': 'Normal'},
    {'name': 'Spike Cannon', 'category': 'Physical', 'power': 20, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'Splash', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Normal'},
    {'name': 'Spore', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 15, 'type': 'Grass'},
    {'name': 'Stomp', 'category': 'Physical', 'power': 65, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Strength', 'category': 'Physical', 'power': 80, 'accuracy': 100, 'pp': 15, 'type': 'Normal'},
    {'name': 'String Shot', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 95, 'pp': 40, 'type': 'Bug'},
    {'name': 'Struggle', 'category': 'Physical', 'power': 50, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Stun Spore', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 75, 'pp': 30, 'type': 'Grass'},
    {'name': 'Submission', 'category': 'Physical', 'power': 80, 'accuracy': 80, 'pp': 25, 'type': 'Fighting'},
    {'name': 'Substitute', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Super Fang', 'category': 'Physical', 'power': 0, 'accuracy': 90, 'pp': 10, 'type': 'Normal'},
    {'name': 'Supersonic', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 55, 'pp': 20, 'type': 'Normal'},
    {'name': 'Surf', 'category': 'Special', 'power': 95, 'accuracy': 100, 'pp': 15, 'type': 'Water'},
    {'name': 'Swift', 'category': 'Physical', 'power': 60, 'accuracy': 0, 'pp': 20, 'type': 'Normal'},
    {'name': 'Swords Dance', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 30, 'type': 'Normal'},
    {'name': 'Tackle', 'category': 'Physical', 'power': 35, 'accuracy': 95, 'pp': 35, 'type': 'Normal'},
    {'name': 'Tail Whip', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 30, 'type': 'Normal'},
    {'name': 'Take Down', 'category': 'Physical', 'power': 90, 'accuracy': 85, 'pp': 20, 'type': 'Normal'},
    {'name': 'Teleport', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 20, 'type': 'Psychic'},
    {'name': 'Thrash', 'category': 'Physical', 'power': 90, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Thunder', 'category': 'Special', 'power': 120, 'accuracy': 70, 'pp': 10, 'type': 'Electric'},
    {'name': 'Thunder Punch', 'category': 'Special', 'power': 75, 'accuracy': 100, 'pp': 15, 'type': 'Electric'},
    {'name': 'Thunder Shock', 'category': 'Special', 'power': 40, 'accuracy': 100, 'pp': 30, 'type': 'Electric'},
    {'name': 'Thunder Wave', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 20, 'type': 'Electric'},
    {'name': 'Thunderbolt', 'category': 'Special', 'power': 95, 'accuracy': 100, 'pp': 15, 'type': 'Electric'},
    {'name': 'Toxic', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 85, 'pp': 10, 'type': 'Poison'},
    {'name': 'Transform', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 10, 'type': 'Normal'},
    {'name': 'Tri Attack', 'category': 'Physical', 'power': 80, 'accuracy': 100, 'pp': 10, 'type': 'Normal'},
    {'name': 'Twineedle', 'category': 'Physical', 'power': 25, 'accuracy': 100, 'pp': 20, 'type': 'Bug'},
    {'name': 'Vice Grip', 'category': 'Physical', 'power': 55, 'accuracy': 100, 'pp': 30, 'type': 'Normal'},
    {'name': 'Vine Whip', 'category': 'Special', 'power': 35, 'accuracy': 100, 'pp': 10, 'type': 'Grass'},
    {'name': 'Water Gun', 'category': 'Special', 'power': 40, 'accuracy': 100, 'pp': 25, 'type': 'Water'},
    {'name': 'Waterfall', 'category': 'Special', 'power': 80, 'accuracy': 100, 'pp': 15, 'type': 'Water'},
    {'name': 'Whirlwind', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 100, 'pp': 20, 'type': 'Normal'},
    {'name': 'Wing Attack', 'category': 'Physical', 'power': 35, 'accuracy': 100, 'pp': 35, 'type': 'Flying'},
    {'name': 'Withdraw', 'category': 'Non-Damaging', 'power': 0, 'accuracy': 0, 'pp': 40, 'type': 'Water'},
    {'name': 'Wrap', 'category': 'Physical', 'power': 15, 'accuracy': 85, 'pp': 20, 'type': 'Normal'}
]

# first gen learnset list
# a pokemon can use only the moves in its learnset
learnset_list = {
    "BULBASAUR" : ["TACKLE","GROWL","LEECHSEED","VINEWHIP","POISONPOWDER","RAZORLEAF","GROWTH","SLEEPPOWDER","SOLARBEAM","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","MEGADRAIN","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "IVYSAUR" : ["TACKLE","GROWL","LEECHSEED","VINEWHIP","POISONPOWDER","RAZORLEAF","GROWTH","SLEEPPOWDER","SOLARBEAM","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","MEGADRAIN","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "VENUSAUR" : ["TACKLE","GROWL","LEECHSEED","VINEWHIP","POISONPOWDER","RAZORLEAF","GROWTH","SLEEPPOWDER","SOLARBEAM","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","MEGADRAIN","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT", "HYPERBEAM"],
    "CHARMANDER" : ["SCRATCH","GROWL","EMBER","LEER","RAGE","SLASH","FLAMETHROWER","FIRESPIN","MEGAPUNCH","SWORDSDANCE","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","DRAGONRAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","FIREBLAST","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","CUT","STRENGTH"],
    "CHARMELEON" : ["SCRATCH","GROWL","EMBER","LEER","RAGE","SLASH","FLAMETHROWER","FIRESPIN","MEGAPUNCH","SWORDSDANCE","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","DRAGONRAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","FIREBLAST","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","CUT","STRENGTH"],
    "CHARIZARD" : ["SCRATCH","GROWL","EMBER","LEER","RAGE","SLASH","FLAMETHROWER","FIRESPIN","MEGAPUNCH","SWORDSDANCE","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","DRAGONRAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","FIREBLAST","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","CUT","STRENGTH","HYPERBEAM","EARTHQUAKE","FISSURE","FLY"],
    "SQUIRTLE" : ["BITE","BLIZZARD","BODYSLAM","BUBBLE","BUBBLEBEAM","COUNTER","DIG","DOUBLEEDGE","DOUBLETEAM","HYDROPUMP","ICEBEAM","MEGAKICK","MEGAPUNCH","MIMIC","REST","SEISMICTOSS","SKULLBASH","STRENGTH","SUBSTITUTE","SURF","TACKLE","TAILWHIP","TOXIC","WATERGUN","WITHDRAW"],
    "WARTORTLE" : ["BITE","BLIZZARD","BODYSLAM","BUBBLE","BUBBLEBEAM","COUNTER","DIG","DOUBLEEDGE","DOUBLETEAM","HYDROPUMP","ICEBEAM","MEGAKICK","MEGAPUNCH","MIMIC","REST","SEISMICTOSS","SKULLBASH","STRENGTH","SUBSTITUTE","SURF","TACKLE","TAILWHIP","TOXIC","WATERGUN","WITHDRAW"],
    "BLASTOISE" : ["BITE","BLIZZARD","BODYSLAM","BUBBLE","BUBBLEBEAM","COUNTER","DIG","DOUBLEEDGE","DOUBLETEAM","HYDROPUMP","ICEBEAM","MEGAKICK","MEGAPUNCH","MIMIC","REST","SEISMICTOSS","SKULLBASH","STRENGTH","SUBSTITUTE","SURF","TACKLE","TAILWHIP","TOXIC","WATERGUN","WITHDRAW","HYPERBEAM","EARTHQUAKE","FISSURE"],
    "CATERPIE" : ["STRINGSHOT","TACKLE"],
    "METAPOD" : ["HARDEN","TACKLE","STRINGSHOT"],
    "BUTTERFREE" : ["CONFUSION","DOUBLEEDGE","DOUBLETEAM","FLASH","GUST","HARDEN","HYPERBEAM","MIMIC","POISONPOWDER","PSYBEAM","PSYCHIC","REST","SLEEPPOWDER","SOLARBEAM","STRINGSHOT","STUNSPORE","SUBSTITUTE","SUPERSONIC","SWIFT","TOXIC","WHIRLWIND","PSYWAVE","MEGADRAIN","RAZORWIND","TAKEDOWN","RAGE","TELEPORT","BIDE"],
    "WEEDLE" : ["POISONSTING","STRINGSHOT"],
    "KAKUNA" : ["HARDEN","POISONSTING","STRINGSHOT"],
    "BEEDRILL" : ["FURYATTACK","FOCUSENERGY","TWINEEDLE","RAGE","PINMISSILE","AGILITY","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","SWIFT","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","HARDEN","POISONSTING","STRINGSHOT"],
    "PIDGEY" : ["AGILITY","DOUBLEEDGE","DOUBLETEAM","FLY","GUST","MIMIC","MIRRORMOVE","QUICKATTACK","REST","SANDATTACK","SUBSTITUTE","SWIFT","TACKLE","TOXIC","WHIRLWIND","WINGATTACK","BIDE","RAZORWIND","RAGE","REFLECT","TAKEDOWN","SKYATTACK"],
    "PIDGEOTTO" : ["AGILITY","DOUBLEEDGE","DOUBLETEAM","FLY","GUST","MIMIC","MIRRORMOVE","QUICKATTACK","REST","SANDATTACK","SUBSTITUTE","SWIFT","TACKLE","TOXIC","WHIRLWIND","WINGATTACK","BIDE","RAZORWIND","RAGE","REFLECT","TAKEDOWN","SKYATTACK"],
    "PIDGEOT" : ["AGILITY","DOUBLEEDGE","DOUBLETEAM","FLY","GUST","MIMIC","MIRRORMOVE","QUICKATTACK","REST","SANDATTACK","SUBSTITUTE","SWIFT","TACKLE","TOXIC","WHIRLWIND","WINGATTACK","BIDE","RAZORWIND","RAGE","REFLECT","TAKEDOWN","SKYATTACK","HYPERBEAM"],
    "RATTATA" : ["TACKLE","TAILWHIP","QUICKATTACK","HYPERFANG","FOCUSENERGY","SUPERFANG","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","DIG","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "RATICATE" : ["TACKLE","TAILWHIP","QUICKATTACK","HYPERFANG","FOCUSENERGY","SUPERFANG","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","DIG","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE", "ICEBEAM", "HYPERBEAM"],
    "SPEAROW" : ["PECK","GROWL","LEER","FURYATTACK","MIRRORMOVE","DRILLPECK","AGILITY","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKYATTACK","REST","SUBSTITUTE","FLY"],
    "FEAROW" : ["PECK","GROWL","LEER","FURYATTACK","MIRRORMOVE","DRILLPECK","AGILITY","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKYATTACK","REST","SUBSTITUTE","FLY","HYPERBEAM"],
    "EKANS" : ["WRAP","LEER","POISONSTING","BITE","GLARE","SCREECH","ACID","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "ARBOK" : ["WRAP","LEER","POISONSTING","BITE","GLARE","SCREECH","ACID","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH","HYPERBEAM"],
    "PIKACHU" : ["AGILITY","BODYSLAM","DOUBLEEDGE","DOUBLETEAM","FLASH","GROWL","LIGHTSCREEN","MEGAKICK","MEGAPUNCH","MIMIC","QUICKATTACK","REST","SEISMICTOSS","SLAM","SUBSTITUTE","SURF","SWIFT","TAILWHIP","THUNDER","THUNDERBOLT","THUNDERSHOCK","THUNDERWAVE","TOXIC","RAGE","PAYDAY","SUBMISSION","BIDE","SKULLBASH"],
    "RAICHU" : ["AGILITY","BODYSLAM","DOUBLEEDGE","DOUBLETEAM","FLASH","GROWL","LIGHTSCREEN","MEGAKICK","MEGAPUNCH","MIMIC","QUICKATTACK","REST","SEISMICTOSS","SLAM","SUBSTITUTE","SURF","SWIFT","TAILWHIP","THUNDER","THUNDERBOLT","THUNDERSHOCK","THUNDERWAVE","TOXIC","RAGE","PAYDAY","SUBMISSION","BIDE","SKULLBASH","HYPERBEAM"],
    "SANDSHREW" : ["SCRATCH","SANDATTACK","SLASH","POISONSTING","TOXIC","FURYSWIPES","SWIFT","SWORDSDANCE","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","CUT","STRENGTH"],
    "SANDSLASH" : ["SCRATCH","SANDATTACK","SLASH","POISONSTING","TOXIC","FURYSWIPES","SWIFT","SWORDSDANCE","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","CUT","STRENGTH","HYPERBEAM"],
    "NIDORAN-F" : ["GROWL","TACKLE","SCRATCH","DOUBLEKICK","POISONSTING","TAILWHIP","BITE","FURYSWIPES","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE"],
    "NIDORINA" : ["GROWL","TACKLE","SCRATCH","DOUBLEKICK","POISONSTING","TAILWHIP","BITE","FURYSWIPES","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","HORNDRILL","BUBBLEBEAM","WATERGUN","ICEBEAM",],
    "NIDOQUEEN" : ["GROWL","TACKLE","SCRATCH","DOUBLEKICK","POISONSTING","TAILWHIP","BITE","FURYSWIPES","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","HORNDRILL","BUBBLEBEAM","WATERGUN","ICEBEAM","MEGAPUNCH","MEGAKICK","HYPERBEAM","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","EARTHQUAKE","FISSURE","FIREBLAST","ROCKSLIDE","SURF"],
    "NIDORAN-M" : ["LEER","TACKLE","HORNATTACK","DOUBLEKICK","POISONSTING","FURYATTACK","FOCUSENERGY","HORNDRILL","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE"],
    "NIDORINO" : ["LEER","TACKLE","HORNATTACK","DOUBLEKICK","POISONSTING","FURYATTACK","FOCUSENERGY","HORNDRILL","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","BUBBLEBEAM","WATERGUN","ICEBEAM",],
    "NIDOKING" : ["LEER","TACKLE","HORNATTACK","DOUBLEKICK","POISONSTING","FURYATTACK","FOCUSENERGY","HORNDRILL","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","BUBBLEBEAM","WATERGUN","ICEBEAM","MEGAPUNCH","MEGAKICK","HYPERBEAM","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","EARTHQUAKE","FISSURE","FIREBLAST","ROCKSLIDE","SURF","THRASH"],
    "CLEFAIRY" : ["POUND","GROWL","SING","DOUBLESLAP","MINIMIZE","METRONOME","DEFENSECURL","LIGHTSCREEN","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH"],
    "CLEFABLE" : ["POUND","GROWL","SING","DOUBLESLAP","MINIMIZE","METRONOME","DEFENSECURL","LIGHTSCREEN","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH","HYPERBEAM"],
    "VULPIX" : ["EMBER","TAILWHIP","QUICKATTACK","ROAR","CONFUSERAY","FLAMETHROWER","FIRESPIN","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "NINETALES" : ["EMBER","TAILWHIP","QUICKATTACK","ROAR","CONFUSERAY","FLAMETHROWER","FIRESPIN","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE","HYPERBEAM"],
    "JIGGLYPUFF" : ["SING","POUND","DISABLE","DEFENSECURL","DOUBLESLAP","REST","BODYSLAM","DOUBLEEDGE","MEGAPUNCH","MEGAKICK","TOXIC","TAKEDOWN","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH"],
    "WIGGLYTUFF" : ["SING","POUND","DISABLE","DEFENSECURL","DOUBLESLAP","REST","BODYSLAM","DOUBLEEDGE","MEGAPUNCH","MEGAKICK","TOXIC","TAKEDOWN","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH","HYPERBEAM"],
    "ZUBAT" : ["LEECHLIFE","SUPERSONIC","BITE","CONFUSERAY","WINGATTACK","HAZE","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","BIDE","SWIFT","REST","SUBSTITUTE"],
    "GOLBAT" : ["LEECHLIFE","SCREECH","SUPERSONIC","BITE","CONFUSERAY","WINGATTACK","HAZE","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","BIDE","SWIFT","REST","SUBSTITUTE","HYPERBEAM"],
    "ODDISH" : ["ABSORB","POISONPOWDER","STUNSPORE","SLEEPPOWDER","ACID","PETALDANCE","SOLARBEAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "GLOOM" : ["ABSORB","POISONPOWDER","STUNSPORE","SLEEPPOWDER","ACID","PETALDANCE","SOLARBEAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "VILEPLUME" : ["ABSORB","POISONPOWDER","STUNSPORE","SLEEPPOWDER","ACID","PETALDANCE","SOLARBEAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT","HYPERBEAM"],
    "PARAS" : ["SCRATCH","STUNSPORE","LEECHLIFE","SPORE","SLASH","GROWTH","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT"],
    "PARASECT" : ["SCRATCH","STUNSPORE","LEECHLIFE","SPORE","SLASH","GROWTH","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","HYPERBEAM"],
    "VENONAT" : ["TACKLE","DISABLE","POISONPOWDER","LEECHLIFE","STUNSPORE","PSYBEAM","SLEEPPOWDER","PSYCHIC","SUPERSONIC","CONFUSION","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","PSYWAVE","SUBSTITUTE","FLASH"],
    "VENOMOTH" : ["TACKLE","DISABLE","POISONPOWDER","LEECHLIFE","STUNSPORE","PSYBEAM","SLEEPPOWDER","PSYCHIC","SUPERSONIC","CONFUSION","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","PSYWAVE","SUBSTITUTE","FLASH","RAZORWIND","WHIRLWIND","HYPERBEAM"],
    "DIGLETT" : ["SCRATCH","GROWL","DIG","SANDATTACK","SLASH","EARTHQUAKE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","FISSURE","MIMIC","DOUBLETEAM","BIDE","REST","ROCKSLIDE","SUBSTITUTE","CUT"],
    "DUGTRIO" : ["SCRATCH","GROWL","DIG","SANDATTACK","SLASH","EARTHQUAKE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","FISSURE","MIMIC","DOUBLETEAM","BIDE","REST","ROCKSLIDE","SUBSTITUTE","CUT","HYPERBEAM"],
    "MEOWTH" : ["SCRATCH","GROWL","BITE","PAYDAY","SCREECH","FURYSWIPES","SLASH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","WATERGUN","BUBBLEBEAM","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "PERSIAN" : ["SCRATCH","GROWL","BITE","PAYDAY","SCREECH","FURYSWIPES","SLASH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","WATERGUN","BUBBLEBEAM","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","HYPERBEAM"],
    "PSYDUCK" : ["SCRATCH","TAILWHIP","DISABLE","CONFUSION","FURYSWIPES","HYDROPUMP","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","DIG","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF","STRENGTH"],
    "GOLDUCK" : ["SCRATCH","TAILWHIP","DISABLE","CONFUSION","FURYSWIPES","HYDROPUMP","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","DIG","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF","STRENGTH","HYPERBEAM"],
    "MANKEY" : ["SCRATCH","LEER","LOWKICK","KARATECHOP","FURYSWIPES","FOCUSENERGY","SEISMICTOSS","THRASH","SCREECH","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","PAYDAY","SUBMISSION","COUNTER","RAGE","THUNDERBOLT","THUNDER","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","SWIFT","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "PRIMEAPE" : ["SCRATCH","LEER","LOWKICK","KARATECHOP","FURYSWIPES","FOCUSENERGY","SEISMICTOSS","THRASH","SCREECH","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","PAYDAY","SUBMISSION","COUNTER","RAGE","THUNDERBOLT","THUNDER","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","SWIFT","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH","HYPERBEAM"],
    "GROWLITHE" : ["BITE","ROAR","EMBER","LEER","TAKEDOWN","AGILITY","FLAMETHROWER","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","DRAGONRAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "ARCANINE" : ["BITE","ROAR","EMBER","LEER","TAKEDOWN","AGILITY","FLAMETHROWER","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","DRAGONRAGE","DIG","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE","TELEPORT","HYPERBEAM"],
    "POLIWAG" : ["BUBBLE","HYPNOSIS","WATERGUN","DOUBLESLAP","BODYSLAM","AMNESIA","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","PSYWAVE","SUBSTITUTE","SURF"],
    "POLIWHIRL" : ["BUBBLE","HYPNOSIS","WATERGUN","DOUBLESLAP","BODYSLAM","AMNESIA","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","PSYWAVE","SUBSTITUTE","SURF","MEGAPUNCH","MEGAKICK","SUBMISSION","COUNTER","SEISMICTOSS","EARTHQUAKE","FISSURE","METRONOME"],
    "POLIWRATH" : ["BUBBLE","HYPNOSIS","WATERGUN","DOUBLESLAP","BODYSLAM","AMNESIA","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","PSYWAVE","SUBSTITUTE","SURF","MEGAPUNCH","MEGAKICK","SUBMISSION","COUNTER","SEISMICTOSS","EARTHQUAKE","FISSURE","METRONOME","HYPERBEAM"],
    "ABRA" : ["TELEPORT","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH"],
    "KADABRA" : ["TELEPORT","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH","CONFUSION","DISABLE","PSYBEAM","RECOVER","DIG"],
    "ALAKAZAM" : ["TELEPORT","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH","CONFUSION","DISABLE","PSYBEAM","RECOVER","DIG","HYPERBEAM"],
    "MACHOP" : ["KARATECHOP","LOWKICK","LEER","FOCUSENERGY","SEISMICTOSS","SUBMISSION","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "MACHOKE" : ["KARATECHOP","LOWKICK","LEER","FOCUSENERGY","SEISMICTOSS","SUBMISSION","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "MACHAMP" : ["KARATECHOP","LOWKICK","LEER","FOCUSENERGY","SEISMICTOSS","SUBMISSION","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "BELLSPROUT" : ["VINEWHIP","GROWTH","WRAP","POISONPOWDER","SLEEPPOWDER","STUNSPORE","ACID","RAZORLEAF","SLAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "WEEPINBELL" : ["VINEWHIP","GROWTH","WRAP","POISONPOWDER","SLEEPPOWDER","STUNSPORE","ACID","RAZORLEAF","SLAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT"],
    "VICTREEBEL" : ["VINEWHIP","GROWTH","WRAP","POISONPOWDER","SLEEPPOWDER","STUNSPORE","ACID","RAZORLEAF","SLAM","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","CUT","HYPERBEAM"],
    "TENTACOOL" : ["ACID","SUPERSONIC","WRAP","POISONSTING","WATERGUN","CONSTRICT","BARRIER","HYDROPUMP","SCREECH","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","SURF"],
    "TENTACRUEL" : ["ACID","SUPERSONIC","WRAP","POISONSTING","WATERGUN","CONSTRICT","BARRIER","HYDROPUMP","SCREECH","SWORDSDANCE","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","MEGADRAIN","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","SURF","HYPERBEAM"],
    "GEODUDE" : ["TACKLE","DEFENSECURL","ROCKTHROW","SELFDESTRUCT","HARDEN","EARTHQUAKE","EXPLOSION","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "GRAVELER" : ["TACKLE","DEFENSECURL","ROCKTHROW","SELFDESTRUCT","HARDEN","EARTHQUAKE","EXPLOSION","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "GOLEM" : ["TACKLE","DEFENSECURL","ROCKTHROW","SELFDESTRUCT","HARDEN","EARTHQUAKE","EXPLOSION","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","METRONOME","FIREBLAST","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH","HYPERBEAM","MEGAKICK"],
    "PONYTA" : ["EMBER","TAILWHIP","STOMP","GROWL","FIRESPIN","TAKEDOWN","AGILITY","TOXIC","HORNDRILL","TAKEDOWN","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "RAPIDASH" : ["EMBER","TAILWHIP","STOMP","GROWL","FIRESPIN","TAKEDOWN","AGILITY","TOXIC","HORNDRILL","TAKEDOWN","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","SUBSTITUTE","HYPERBEAM"],
    "SLOWPOKE" : ["CONFUSION","DISABLE","HEADBUTT","GROWL","WATERGUN","AMNESIA","PSYCHIC","TOXIC","TAKEDOWN","DOUBLEEDGE","BODYSLAM","BUBBLEBEAM","ICEBEAM","BLIZZARD","PAYDAY","RAGE","EARTHQUAKE","FISSURE","DIG","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","SURF","STRENGTH","FLASH"],
    "SLOWBRO" : ["CONFUSION","DISABLE","HEADBUTT","GROWL","WATERGUN","WITHDRAW","AMNESIA","PSYCHIC","MEGAPUNCH","MEGAKICK","TOXIC","TAKEDOWN","DOUBLEEDGE","BODYSLAM","BUBBLEBEAM","ICEBEAM","BLIZZARD","PAYDAY","RAGE","EARTHQUAKE","FISSURE","DIG","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","SURF","STRENGTH","FLASH","SUBMISSION","COUNTER","SEISMICTOSS","HYPERBEAM"],
    "MAGNEMITE" : ["TACKLE","SONICBOOM","THUNDERSHOCK","SUPERSONIC","THUNDERWAVE","SWIFT","SCREECH","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","THUNDERBOLT","THUNDER","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","REST","SUBSTITUTE","FLASH"],
    "MAGNETON" : ["TACKLE","SONICBOOM","THUNDERSHOCK","SUPERSONIC","THUNDERWAVE","SWIFT","SCREECH","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","THUNDERBOLT","THUNDER","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","REST","SUBSTITUTE","FLASH","HYPERBEAM"],
    "FARFETCH\'D" : ["PECK","SANDATTACK","LEER","FURYATTACK","SWORDSDANCE","AGILITY","SLASH","RAZORWIND","WHIRLWIND","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","CUT","FLY"],
    "DODUO" : ["PECK","GROWL","FURYATTACK","DRILLPECK","RAGE","TRIATTACK","AGILITY","WHIRLWIND","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","SKYATTACK","REST","SUBSTITUTE","FLY"],
    "DODRIO" : ["PECK","GROWL","FURYATTACK","DRILLPECK","RAGE","TRIATTACK","AGILITY","WHIRLWIND","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","SKYATTACK","REST","SUBSTITUTE","FLY","HYPERBEAM"],
    "SEEL" : ["HEADBUTT","GROWL","AURORABEAM","REST","TAKEDOWN","ICEBEAM","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","PAYDAY","RAGE","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","SUBSTITUTE","SURF","STRENGTH"],
    "DEWGONG" : ["HEADBUTT","GROWL","AURORABEAM","REST","TAKEDOWN","ICEBEAM","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","PAYDAY","RAGE","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","SUBSTITUTE","SURF","STRENGTH","HYPERBEAM"],
    "GRIMER" : ["POUND","DISABLE","POISONGAS","MINIMIZE","SLUDGE","HARDEN","SCREECH","ACIDARMOR","TOXIC","BODYSLAM","RAGE","MEGADRAIN","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","FIREBLAST","REST","EXPLOSION","SUBSTITUTE"],
    "MUK" : ["POUND","DISABLE","POISONGAS","MINIMIZE","SLUDGE","HARDEN","SCREECH","ACIDARMOR","TOXIC","BODYSLAM","RAGE","MEGADRAIN","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","FIREBLAST","REST","EXPLOSION","SUBSTITUTE","HYPERBEAM"],
    "SHELLDER" : ["TACKLE","WITHDRAW","SUPERSONIC","CLAMP","AURORABEAM","LEER","ICEBEAM","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","RAGE","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SELFDESTRUCT","SWIFT","REST","EXPLOSION","TRIATTACK","SUBSTITUTE","SURF"],
    "CLOYSTER" : ["TACKLE","WITHDRAW","SUPERSONIC","CLAMP","AURORABEAM","LEER","ICEBEAM","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","BLIZZARD","RAGE","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SELFDESTRUCT","SWIFT","REST","EXPLOSION","TRIATTACK","SUBSTITUTE","SURF","SPIKECANNON","HYPERBEAM"],
    "GASTLY" : ["LICK","CONFUSERAY","HYPNOSIS","NIGHTSHADE","DREAMEATER","TOXIC","RAGE","MEGADRAIN","THUNDERBOLT","THUNDER","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","REST","PSYWAVE","SUBSTITUTE","EXPLOSION"],
    "HAUNTER" : ["LICK","CONFUSERAY","HYPNOSIS","NIGHTSHADE","DREAMEATER","TOXIC","RAGE","MEGADRAIN","THUNDERBOLT","THUNDER","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","REST","PSYWAVE","SUBSTITUTE","EXPLOSION"],
    "GENGAR" : ["LICK","CONFUSERAY","HYPNOSIS","NIGHTSHADE","DREAMEATER","TOXIC","RAGE","MEGADRAIN","THUNDERBOLT","THUNDER","PSYCHIC","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","REST","PSYWAVE","SUBSTITUTE","EXPLOSION","MEGAPUNCH","MEGAKICK","DOUBLEEDGE","BODYSLAM","TAKEDOWN","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","METRONOME","SKULLBASH","STRENGTH"],
    "ONIX" : ["TACKLE","SCREECH","BIND","ROCKTHROW","RAGE","SLAM","HARDEN","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","REST","EXPLOSION","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "DROWZEE" : ["POUND","HYPNOSIS","DISABLE","CONFUSION","HEADBUTT","POISONGAS","MEDITATE","PSYCHIC","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","DREAMEATER","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH"],
    "HYPNO" : ["POUND","HYPNOSIS","DISABLE","CONFUSION","HEADBUTT","POISONGAS","MEDITATE","PSYCHIC","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","DREAMEATER","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH","HYPERBEAM"],
    "KRABBY" : ["BUBBLE","LEER","VICEGRIP","GUILLOTINE","STOMP","CRABHAMMER","HARDEN","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","SURF","STRENGTH"],
    "KINGLER" : ["BUBBLE","LEER","VICEGRIP","GUILLOTINE","STOMP","CRABHAMMER","HARDEN","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT","SURF","STRENGTH","HYPERBEAM"],
    "VOLTORB" : ["TACKLE","SCREECH","SONICBOOM","SELFDESTRUCT","LIGHTSCREEN","SWIFT","EXPLOSION","TOXIC","TAKEDOWN","THUNDERBOLT","THUNDER","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","THUNDERWAVE","SUBSTITUTE","FLASH"],
    "ELECTRODE" : ["TACKLE","SCREECH","SONICBOOM","SELFDESTRUCT","LIGHTSCREEN","SWIFT","EXPLOSION","TOXIC","TAKEDOWN","THUNDERBOLT","THUNDER","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","THUNDERWAVE","SUBSTITUTE","FLASH","HYPERBEAM"],
    "EXEGGCUTE" : ["BARRAGE","HYPNOSIS","REFLECT","LEECHSEED","STUNSPORE","POISONPOWDER","SOLARBEAM","SLEEPPOWDER","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SELFDESTRUCT","EGGBOMB","REST","PSYWAVE","SUBSTITUTE","EXPLOSION"],
    "EXEGGUTOR" : ["BARRAGE","HYPNOSIS","REFLECT","LEECHSEED","STUNSPORE","POISONPOWDER","SOLARBEAM","SLEEPPOWDER","TOXIC","TAKEDOWN","DOUBLEEDGE","RAGE","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SELFDESTRUCT","EGGBOMB","REST","PSYWAVE","SUBSTITUTE","EXPLOSION","STOMP","MEGADRAIN","HYPERBEAM"],
    "CUBONE" : ["GROWL","BONECLUB","TAILWHIP","HEADBUTT","LEER","FOCUSENERGY","THRASH","BONEMERANG","RAGE","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","SUBSTITUTE","STRENGTH"],
    "MAROWAK" : ["GROWL","BONECLUB","TAILWHIP","HEADBUTT","LEER","FOCUSENERGY","THRASH","BONEMERANG","RAGE","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","SUBSTITUTE","STRENGTH","HYPERBEAM"],
    "HITMONLEE" : ["DOUBLEKICK","MEDITATE","ROLLINGKICK","JUMPKICK","FOCUSENERGY","HIGHJUMPKICK","MEGAKICK","MEGAPUNCH","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","MIMIC","DOUBLETEAM","BIDE","METRONOME","SWIFT","SKULLBASH","REST","SUBSTITUTE","STRENGTH"],
    "HITMONCHAN" : ["COMETPUNCH","AGILITY","FIREPUNCH","THUNDERPUNCH","ICEPUNCH","MEGAPUNCH","COUNTER","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","COUNTER","SUBMISSION","SEISMICTOSS","RAGE","MIMIC","DOUBLETEAM","BIDE","METRONOME","SWIFT","SKULLBASH","REST","SUBSTITUTE","STRENGTH"],
    "LICKITUNG" : ["WRAP","SUPERSONIC","STOMP","DISABLE","DEFENSECURL","SLAM","SCREECH","MEGAPUNCH","SWORDSDANCE","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","SUBSTITUTE","CUT","SURF","STRENGTH"],
    "KOFFING" : ["TACKLE","SMOG","SLUDGE","SMOKESCREEN","SELFDESTRUCT","HAZE","EXPLOSION","TOXIC","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","FIREBLAST","REST","EXPLOSION","SUBSTITUTE"],
    "WEEZING" : ["TACKLE","SMOG","SLUDGE","SMOKESCREEN","SELFDESTRUCT","HAZE","EXPLOSION","TOXIC","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","BIDE","SELFDESTRUCT","FIREBLAST","REST","EXPLOSION","SUBSTITUTE","HYPERBEAM"],
    "RHYHORN" : ["HORNATTACK","TAILWHIP","STOMP","FURYATTACK","HORNDRILL","LEER","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH"],
    "RHYDON" : ["HORNATTACK","TAILWHIP","STOMP","FURYATTACK","HORNDRILL","LEER","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","DIG","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","STRENGTH","MEGAPUNCH","MEGAKICK","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","SURF"],
    "CHANSEY" : ["POUND","DOUBLESLAP","SING","GROWL","MINIMIZE","DEFENSECURL","LIGHTSCREEN","DOUBLEEDGE","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","THUNDERWAVE","REFLECT","BIDE","METRONOME","FIREBLAST","EGGBOMB","SKULLBASH","SOFTBOILED","REST","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH"],
    "TANGELA" : ["CONSTRICT","BIND","ABSORB","VINEWHIP","POISONPOWDER","STUNSPORE","SLEEPPOWDER","SLAM","GROWTH","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","RAGE","MEGADRAIN","SOLARBEAM","MIMIC","DOUBLETEAM","BIDE","SKULLBASH","REST","SUBSTITUTE","CUT"],
    "KANGASKHAN" : ["COMETPUNCH","RAGE","BITE","TAILWHIP","MEGAPUNCH","LEER","DIZZYPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","ROCKSLIDE","SUBSTITUTE","SURF","STRENGTH"],
    "HORSEA" : ["BUBBLE","SMOKESCREEN","LEER","WATERGUN","AGILITY","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF"],
    "SEADRA" : ["BUBBLE","SMOKESCREEN","LEER","WATERGUN","AGILITY","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF","HYPERBEAM"],
    "GOLDEEN" : ["PECK","TAILWHIP","SUPERSONIC","HORNATTACK","FURYATTACK","WATERFALL","HORNDRILL","AGILITY","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF"],
    "SEAKING" : ["PECK","TAILWHIP","SUPERSONIC","HORNATTACK","FURYATTACK","WATERFALL","HORNDRILL","AGILITY","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","SURF","HYPERBEAM"],
    "STARYU" : ["TACKLE","WATERGUN","HARDEN","RECOVER","SWIFT","MINIMIZE","LIGHTSCREEN","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","SURF","STRENGTH"],
    "STARMIE" : ["TACKLE","WATERGUN","HARDEN","RECOVER","SWIFT","MINIMIZE","LIGHTSCREEN","HYDROPUMP","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","SURF","STRENGTH","HYPERBEAM"],
    "MR. MIME" : ["CONFUSION","BARRIER","LIGHTSCREEN","DOUBLESLAP","MEDITATE","SUBSTITUTE","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","SUBSTITUTE","FLASH"],
    "SCYTHER" : ["QUICKATTACK","LEER","FOCUSENERGY","DOUBLETEAM","SLASH","SWORDSDANCE","AGILITY","WINGATTACK","TOXIC","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","RAGE","MIMIC","DOUBLETEAM","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","CUT"],
    "JYNX" : ["POUND","LOVELYKISS","LICK","DOUBLESLAP","ICEPUNCH","BODYSLAM","THRASH","BLIZZARD","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SKULLBASH","REST","PSYWAVE","SUBSTITUTE"],
    "ELECTABUZZ" : ["QUICKATTACK","LEER","THUNDERPUNCH","THUNDERSHOCK","SCREECH","LIGHTSCREEN","THUNDER","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","SUBSTITUTE","STRENGTH","FLASH"],
    "MAGMAR" : ["EMBER","LEER","CONFUSERAY","FIREPUNCH","SMOKESCREEN","SMOG","FLAMETHROWER","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","PSYCHIC","TELEPORT","DOUBLETEAM","REFLECT","METRONOME","FIREBLAST","SKULLBASH","REST","PSYWAVE","SUBSTITUTE","STRENGTH"],
    "PINSIR" : ["VICEGRIP","SEISMICTOSS","GUILLOTINE","FOCUSENERGY","HARDEN","SLASH","SWORDSDANCE","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","SUBMISSION","RAGE","MIMIC","DOUBLETEAM","BIDE","REST","SUBSTITUTE","CUT","STRENGTH"],
    "TAUROS" : ["TACKLE","STOMP","TAILWHIP","LEER","RAGE","TAKEDOWN","TOXIC","HORNDRILL","TAKEDOWN","DOUBLEEDGE","ICEBEAM","BLIZZARD","HYPERBEAM","RAGE","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","MIMIC","DOUBLETEAM","BIDE","FIREBLAST","SKULLBASH","REST","SUBSTITUTE","STRENGTH"],
    "MAGIKARP" : ["SPLASH","TACKLE"],
    "GYARADOS" : ["SPLASH","TACKLE","BITE","DRAGONRAGE","LEER","HYDROPUMP","HYPERBEAM","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","WATERGUN","BUBBLEBEAM","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SKULLBASH","REST","SURF","STRENGTH","SUBSTITUTE"],
    "LAPRAS" : ["WATERGUN","GROWL","SING","MIST","BODYSLAM","CONFUSERAY","ICEBEAM","HYDROPUMP","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","HORNDRILL","BUBBLEBEAM","BLIZZARD","RAGE","SOLARBEAM","DRAGONRAGE","THUNDERBOLT","THUNDER","PSYCHIC","MIMIC","DOUBLETEAM","REFLECT","BIDE","SKULLBASH","REST","PSYWAVE","SUBSTITUTE","SURF","STRENGTH"],
    "DITTO" : ["TRANSFORM"],
    "EEVEE" : ["TACKLE","TAILWHIP","SANDATTACK","GROWL","QUICKATTACK","BITE","FOCUSENERGY","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE"],
    "VAPOREON" : ["TACKLE","TAILWHIP","SANDATTACK","GROWL","QUICKATTACK","BITE","FOCUSENERGY","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","WATERGUN","ACIDARMOR","HAZE","MIST","HYDROPUMP","BUBBLEBEAM","ICEBEAM","BLIZZARD","SURF","HYPERBEAM"],
    "JOLTEON" : ["TACKLE","TAILWHIP","SANDATTACK","GROWL","QUICKATTACK","BITE","FOCUSENERGY","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","THUNDERSHOCK","THUNDERWAVE","DOUBLEKICK","AGILITY","PINMISSILE","THUNDERBOLT","THUNDER","HYPERBEAM"],
    "FLAREON" : ["TACKLE","TAILWHIP","SANDATTACK","GROWL","QUICKATTACK","BITE","FOCUSENERGY","TAKEDOWN","TOXIC","BODYSLAM","DOUBLEEDGE","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","SUBSTITUTE","HYPERBEAM","EMBER","FIRESPIN","FLAMETHROWER","FIREBLAST","SMOG"],
    "PORYGON" : ["TACKLE","SHARPEN","CONVERSION","PSYBEAM","RECOVER","AGILITY","TRIATTACK","TOXIC","TAKEDOWN","DOUBLEEDGE","ICEBEAM","BLIZZARD","HYPERBEAM","RAGE","THUNDERBOLT","THUNDER","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","FLASH"],
    "OMANYTE" : ["WATERGUN","WITHDRAW","HORNATTACK","LEER","SPIKECANNON","HYDROPUMP","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","REFLECT","BIDE","REST","SUBSTITUTE","SURF"],
    "OMASTAR" : ["WATERGUN","WITHDRAW","HORNATTACK","LEER","SPIKECANNON","HYDROPUMP","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","REFLECT","BIDE","REST","SUBSTITUTE","SURF","HYPERBEAM","SUBMISSION","SEISMICTOSS"],
    "KABUTO" : ["ABSORB","SCRATCH","SLASH","HARDEN","LEER","HYDROPUMP","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","SURF"],
    "KABUTOPS" : ["ABSORB","SCRATCH","SLASH","HARDEN","LEER","HYDROPUMP","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","REST","SUBSTITUTE","SURF","RAZORWIND","SWORDSDANCE","MEGAKICK","SUBMISSION","SEISMICTOSS","CUT","HYPERBEAM"],
    "AERODACTYL" : ["WINGATTACK","AGILITY","SUPERSONIC","BITE","TAKEDOWN","HYPERBEAM","RAGE","DRAGONRAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKYATTACK","REST","SUBSTITUTE","FLY"],
    "SNORLAX" : ["AMNESIA","HEADBUTT","REST","BODYSLAM","HARDEN","DOUBLEEDGE","HYPERBEAM","MEGAPUNCH","MEGAKICK","TOXIC","TAKEDOWN","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","PSYCHIC","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SELFDESTRUCT","FIREBLAST","SKULLBASH","REST","PSYWAVE","ROCKSLIDE","SUBSTITUTE","SURF","STRENGTH"],
    "ARTICUNO" : ["PECK","ICEBEAM","BLIZZARD","AGILITY","MIST","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","HYPERBEAM","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKYATTACK","REST","SUBSTITUTE","FLY"],
    "ZAPDOS" : ["THUNDERSHOCK","DRILLPECK","AGILITY","THUNDER","LIGHTSCREEN","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","RAGE","THUNDERBOLT","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","SKYATTACK","REST","THUNDERWAVE","SUBSTITUTE","FLY","FLASH"],
    "MOLTRES" : ["PECK","FIRESPIN","LEER","AGILITY","SKYATTACK","RAZORWIND","WHIRLWIND","TOXIC","TAKEDOWN","DOUBLEEDGE","HYPERBEAM","RAGE","MIMIC","DOUBLETEAM","REFLECT","BIDE","SWIFT","FIREBLAST","REST","SUBSTITUTE","FLY"],
    "DRATINI" : ["WRAP","LEER","THUNDERWAVE","AGILITY","SLAM","DRAGONRAGE","HYPERBEAM","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","THUNDERWAVE","SUBSTITUTE","SURF"],
    "DRAGONAIR" : ["WRAP","LEER","THUNDERWAVE","AGILITY","SLAM","DRAGONRAGE","HYPERBEAM","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","THUNDERWAVE","SUBSTITUTE","SURF"],
    "DRAGONITE" : ["WRAP","LEER","THUNDERWAVE","AGILITY","SLAM","DRAGONRAGE","HYPERBEAM","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","RAGE","THUNDERBOLT","THUNDER","MIMIC","DOUBLETEAM","REFLECT","BIDE","FIREBLAST","SWIFT","SKULLBASH","REST","THUNDERWAVE","SUBSTITUTE","SURF","RAZORWIND","STRENGTH"],
    "MEWTWO" : ["CONFUSION","DISABLE","SWIFT","PSYCHIC","BARRIER","RECOVER","MIST","AMNESIA","MEGAPUNCH","MEGAKICK","TOXIC","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","SOLARBEAM","THUNDERBOLT","THUNDER","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SELFDESTRUCT","FIREBLAST","SKULLBASH","REST","THUNDERWAVE","PSYWAVE","TRIATTACK","SUBSTITUTE","STRENGTH","FLASH"],
    "MEW" : ["POUND","TRANSFORM","MEGAPUNCH","METRONOME","PSYCHIC","RAZORWIND","SWORDSDANCE","WHIRLWIND","MEGAKICK","TOXIC","HORNDRILL","BODYSLAM","TAKEDOWN","DOUBLEEDGE","BUBBLEBEAM","WATERGUN","ICEBEAM","BLIZZARD","HYPERBEAM","PAYDAY","SUBMISSION","COUNTER","SEISMICTOSS","RAGE","MEGADRAIN","DRAGONRAGE","SOLARBEAM","THUNDERBOLT","THUNDER","EARTHQUAKE","FISSURE","DIG","PSYCHIC","TELEPORT","MIMIC","DOUBLETEAM","REFLECT","BIDE","METRONOME","SELFDESTRUCT","EGGBOMB","FIREBLAST","SWIFT","SOFTBOILED","SKULLBASH","DREAMEATER","SKYATTACK","REST","THUNDERWAVE","PSYWAVE","EXPLOSION","ROCKSLIDE","TRIATTACK","SUBSTITUTE","CUT","FLY","SURF","STRENGTH","FLASH"],
}

# checks if a certain move is compatible
# with a pokemon, based on the learnset list
def check_compatibility(move, pkmn):
    move = move.upper().replace(' ', '')
    if move in learnset_list[pkmn.upper()]:
        return True
    else:
        return False