from app.schemas.pokemon import Pokemon, Stats
from app.schemas.typing import Typing

pokedex = [
    Pokemon(id=1, name="Bulbasaur", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=45, attack=49, defense=49, sp_attack=65, sp_defense=65, speed=45)),
    Pokemon(id=2, name="Ivysaur", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=60, attack=62, defense=63, sp_attack=80, sp_defense=80, speed=60)),
    Pokemon(id=3, name="Venusaur", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=80, attack=82, defense=83, sp_attack=100, sp_defense=100, speed=80)),
    Pokemon(id=4, name="Charmander", typing=[Typing.FIRE], base_stats=Stats(hp=39, attack=52, defense=43, sp_attack=50, sp_defense=50, speed=65)),
    Pokemon(id=5, name="Charmeleon", typing=[Typing.FIRE], base_stats=Stats(hp=58, attack=64, defense=58, sp_attack=65, sp_defense=65, speed=80)),
    Pokemon(id=6, name="Charizard", typing=[Typing.FIRE, Typing.FLYING], base_stats=Stats(hp=78, attack=84, defense=78, sp_attack=85, sp_defense=85, speed=100)),
    Pokemon(id=7, name="Squirtle", typing=[Typing.WATER], base_stats=Stats(hp=44, attack=48, defense=65, sp_attack=50, sp_defense=50, speed=43)),
    Pokemon(id=8, name="Wartortle", typing=[Typing.WATER], base_stats=Stats(hp=59, attack=63, defense=80, sp_attack=65, sp_defense=65, speed=58)),
    Pokemon(id=9, name="Blastoise", typing=[Typing.WATER], base_stats=Stats(hp=79, attack=83, defense=100, sp_attack=85, sp_defense=85, speed=78)),
    Pokemon(id=10, name="Caterpie", typing=[Typing.BUG], base_stats=Stats(hp=45, attack=30, defense=35, sp_attack=20, sp_defense=20, speed=45)),
    Pokemon(id=11, name="Metapod", typing=[Typing.BUG], base_stats=Stats(hp=50, attack=20, defense=55, sp_attack=25, sp_defense=25, speed=30)),
    Pokemon(id=12, name="Butterfree", typing=[Typing.BUG, Typing.FLYING], base_stats=Stats(hp=60, attack=45, defense=50, sp_attack=80, sp_defense=80, speed=70)),
    Pokemon(id=13, name="Weedle", typing=[Typing.BUG, Typing.POISON], base_stats=Stats(hp=40, attack=35, defense=30, sp_attack=20, sp_defense=20, speed=50)),
    Pokemon(id=14, name="Kakuna", typing=[Typing.BUG, Typing.POISON], base_stats=Stats(hp=45, attack=25, defense=50, sp_attack=25, sp_defense=25, speed=35)),
    Pokemon(id=15, name="Beedrill", typing=[Typing.BUG, Typing.POISON], base_stats=Stats(hp=65, attack=80, defense=40, sp_attack=45, sp_defense=45, speed=75)),
    Pokemon(id=16, name="Pidgey", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=40, attack=45, defense=40, sp_attack=35, sp_defense=35, speed=56)),
    Pokemon(id=17, name="Pidgeotto", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=63, attack=60, defense=55, sp_attack=50, sp_defense=50, speed=71)),
    Pokemon(id=18, name="Pidgeot", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=83, attack=80, defense=75, sp_attack=70, sp_defense=70, speed=91)),
    Pokemon(id=19, name="Rattata", typing=[Typing.NORMAL], base_stats=Stats(hp=30, attack=56, defense=35, sp_attack=25, sp_defense=25, speed=72)),
    Pokemon(id=20, name="Raticate", typing=[Typing.NORMAL], base_stats=Stats(hp=55, attack=81, defense=60, sp_attack=50, sp_defense=50, speed=97)),
    Pokemon(id=21, name="Spearow", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=40, attack=60, defense=30, sp_attack=31, sp_defense=31, speed=70)),
    Pokemon(id=22, name="Fearow", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=65, attack=90, defense=65, sp_attack=61, sp_defense=61, speed=100)),
    Pokemon(id=23, name="Ekans", typing=[Typing.POISON], base_stats=Stats(hp=35, attack=60, defense=44, sp_attack=40, sp_defense=40, speed=55)),
    Pokemon(id=24, name="Arbok", typing=[Typing.POISON], base_stats=Stats(hp=60, attack=85, defense=69, sp_attack=65, sp_defense=65, speed=80)),
    Pokemon(id=25, name="Pikachu", typing=[Typing.ELECTRIC], base_stats=Stats(hp=35, attack=55, defense=30, sp_attack=50, sp_defense=50, speed=90)),
    Pokemon(id=26, name="Raichu", typing=[Typing.ELECTRIC], base_stats=Stats(hp=60, attack=90, defense=55, sp_attack=90, sp_defense=90, speed=110)),
    Pokemon(id=27, name="Sandshrew", typing=[Typing.GROUND], base_stats=Stats(hp=50, attack=75, defense=85, sp_attack=30, sp_defense=30, speed=40)),
    Pokemon(id=28, name="Sandslash", typing=[Typing.GROUND], base_stats=Stats(hp=75, attack=100, defense=110, sp_attack=55, sp_defense=55, speed=65)),
    Pokemon(id=29, name="Nidoran-F", typing=[Typing.POISON], base_stats=Stats(hp=55, attack=47, defense=52, sp_attack=40, sp_defense=40, speed=41)),
    Pokemon(id=30, name="Nidorina", typing=[Typing.POISON], base_stats=Stats(hp=70, attack=62, defense=67, sp_attack=55, sp_defense=55, speed=56)),
    Pokemon(id=31, name="Nidoqueen", typing=[Typing.POISON, Typing.GROUND], base_stats=Stats(hp=90, attack=82, defense=87, sp_attack=75, sp_defense=75, speed=76)),
    Pokemon(id=32, name="Nidoran-M", typing=[Typing.POISON], base_stats=Stats(hp=46, attack=57, defense=40, sp_attack=40, sp_defense=40, speed=50)),
    Pokemon(id=33, name="Nidorino", typing=[Typing.POISON], base_stats=Stats(hp=61, attack=72, defense=57, sp_attack=55, sp_defense=55, speed=65)),
    Pokemon(id=34, name="Nidoking", typing=[Typing.POISON, Typing.GROUND], base_stats=Stats(hp=81, attack=92, defense=77, sp_attack=75, sp_defense=75, speed=85)),
    Pokemon(id=35, name="Clefairy", typing=[Typing.NORMAL], base_stats=Stats(hp=70, attack=45, defense=48, sp_attack=60, sp_defense=60, speed=35)),
    Pokemon(id=36, name="Clefable", typing=[Typing.NORMAL], base_stats=Stats(hp=95, attack=70, defense=73, sp_attack=85, sp_defense=85, speed=60)),
    Pokemon(id=37, name="Vulpix", typing=[Typing.FIRE], base_stats=Stats(hp=38, attack=41, defense=40, sp_attack=65, sp_defense=65, speed=65)),
    Pokemon(id=38, name="Ninetales", typing=[Typing.FIRE], base_stats=Stats(hp=73, attack=76, defense=75, sp_attack=100, sp_defense=100, speed=100)),
    Pokemon(id=39, name="Jigglypuff", typing=[Typing.NORMAL], base_stats=Stats(hp=115, attack=45, defense=20, sp_attack=25, sp_defense=25, speed=20)),
    Pokemon(id=40, name="Wigglytuff", typing=[Typing.NORMAL], base_stats=Stats(hp=140, attack=70, defense=45, sp_attack=50, sp_defense=50, speed=45)),
    Pokemon(id=41, name="Zubat", typing=[Typing.POISON, Typing.FLYING], base_stats=Stats(hp=40, attack=45, defense=35, sp_attack=40, sp_defense=40, speed=55)),
    Pokemon(id=42, name="Golbat", typing=[Typing.POISON, Typing.FLYING], base_stats=Stats(hp=75, attack=80, defense=70, sp_attack=75, sp_defense=75, speed=90)),
    Pokemon(id=43, name="Oddish", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=45, attack=50, defense=55, sp_attack=75, sp_defense=75, speed=30)),
    Pokemon(id=44, name="Gloom", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=60, attack=65, defense=70, sp_attack=85, sp_defense=85, speed=40)),
    Pokemon(id=45, name="Vileplume", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=75, attack=80, defense=85, sp_attack=100, sp_defense=100, speed=50)),
    Pokemon(id=46, name="Paras", typing=[Typing.BUG, Typing.GRASS], base_stats=Stats(hp=35, attack=70, defense=55, sp_attack=55, sp_defense=55, speed=25)),
    Pokemon(id=47, name="Parasect", typing=[Typing.BUG, Typing.GRASS], base_stats=Stats(hp=60, attack=95, defense=80, sp_attack=80, sp_defense=80, speed=30)),
    Pokemon(id=48, name="Venonat", typing=[Typing.BUG, Typing.POISON], base_stats=Stats(hp=60, attack=55, defense=50, sp_attack=40, sp_defense=40, speed=45)),
    Pokemon(id=49, name="Venomoth", typing=[Typing.BUG, Typing.POISON], base_stats=Stats(hp=70, attack=65, defense=60, sp_attack=90, sp_defense=90, speed=90)),
    Pokemon(id=50, name="Diglett", typing=[Typing.GROUND], base_stats=Stats(hp=10, attack=55, defense=25, sp_attack=45, sp_defense=45, speed=95)),
    Pokemon(id=51, name="Dugtrio", typing=[Typing.GROUND], base_stats=Stats(hp=35, attack=80, defense=50, sp_attack=70, sp_defense=70, speed=120)),
    Pokemon(id=52, name="Meowth", typing=[Typing.NORMAL], base_stats=Stats(hp=40, attack=45, defense=35, sp_attack=40, sp_defense=40, speed=90)),
    Pokemon(id=53, name="Persian", typing=[Typing.NORMAL], base_stats=Stats(hp=65, attack=70, defense=60, sp_attack=65, sp_defense=65, speed=115)),
    Pokemon(id=54, name="Psyduck", typing=[Typing.WATER], base_stats=Stats(hp=50, attack=52, defense=48, sp_attack=50, sp_defense=50, speed=55)),
    Pokemon(id=55, name="Golduck", typing=[Typing.WATER], base_stats=Stats(hp=80, attack=82, defense=78, sp_attack=80, sp_defense=80, speed=85)),
    Pokemon(id=56, name="Mankey", typing=[Typing.FIGHTING], base_stats=Stats(hp=40, attack=80, defense=35, sp_attack=35, sp_defense=35, speed=70)),
    Pokemon(id=57, name="Primeape", typing=[Typing.FIGHTING], base_stats=Stats(hp=65, attack=105, defense=60, sp_attack=60, sp_defense=60, speed=95)),
    Pokemon(id=58, name="Growlithe", typing=[Typing.FIRE], base_stats=Stats(hp=55, attack=70, defense=45, sp_attack=50, sp_defense=50, speed=60)),
    Pokemon(id=59, name="Arcanine", typing=[Typing.FIRE], base_stats=Stats(hp=90, attack=110, defense=80, sp_attack=80, sp_defense=80, speed=95)),
    Pokemon(id=60, name="Poliwag", typing=[Typing.WATER], base_stats=Stats(hp=40, attack=50, defense=40, sp_attack=40, sp_defense=40, speed=90)),
    Pokemon(id=61, name="Poliwhirl", typing=[Typing.WATER], base_stats=Stats(hp=65, attack=65, defense=65, sp_attack=50, sp_defense=50, speed=90)),
    Pokemon(id=62, name="Poliwrath", typing=[Typing.WATER, Typing.FIGHTING], base_stats=Stats(hp=90, attack=85, defense=95, sp_attack=70, sp_defense=70, speed=70)),
    Pokemon(id=63, name="Abra", typing=[Typing.PSYCHIC], base_stats=Stats(hp=25, attack=20, defense=15, sp_attack=105, sp_defense=105, speed=90)),
    Pokemon(id=64, name="Kadabra", typing=[Typing.PSYCHIC], base_stats=Stats(hp=40, attack=35, defense=30, sp_attack=120, sp_defense=120, speed=105)),
    Pokemon(id=65, name="Alakazam", typing=[Typing.PSYCHIC], base_stats=Stats(hp=55, attack=50, defense=45, sp_attack=135, sp_defense=135, speed=120)),
    Pokemon(id=66, name="Machop", typing=[Typing.FIGHTING], base_stats=Stats(hp=70, attack=80, defense=50, sp_attack=35, sp_defense=35, speed=35)),
    Pokemon(id=67, name="Machoke", typing=[Typing.FIGHTING], base_stats=Stats(hp=80, attack=100, defense=70, sp_attack=50, sp_defense=50, speed=45)),
    Pokemon(id=68, name="Machamp", typing=[Typing.FIGHTING], base_stats=Stats(hp=90, attack=130, defense=80, sp_attack=65, sp_defense=65, speed=55)),
    Pokemon(id=69, name="Bellsprout", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=50, attack=75, defense=35, sp_attack=70, sp_defense=70, speed=40)),
    Pokemon(id=70, name="Weepinbell", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=65, attack=90, defense=50, sp_attack=85, sp_defense=85, speed=55)),
    Pokemon(id=71, name="Victreebel", typing=[Typing.GRASS, Typing.POISON], base_stats=Stats(hp=80, attack=105, defense=65, sp_attack=100, sp_defense=100, speed=70)),
    Pokemon(id=72, name="Tentacool", typing=[Typing.WATER, Typing.POISON], base_stats=Stats(hp=40, attack=40, defense=35, sp_attack=50, sp_defense=100, speed=70)),
    Pokemon(id=73, name="Tentacruel", typing=[Typing.WATER, Typing.POISON], base_stats=Stats(hp=80, attack=70, defense=65, sp_attack=80, sp_defense=120, speed=100)),
    Pokemon(id=74, name="Geodude", typing=[Typing.ROCK, Typing.GROUND], base_stats=Stats(hp=40, attack=80, defense=100, sp_attack=30, sp_defense=30, speed=20)),
    Pokemon(id=75, name="Graveler", typing=[Typing.ROCK, Typing.GROUND], base_stats=Stats(hp=55, attack=95, defense=115, sp_attack=45, sp_defense=45, speed=35)),
    Pokemon(id=76, name="Golem", typing=[Typing.ROCK, Typing.GROUND], base_stats=Stats(hp=80, attack=120, defense=130, sp_attack=55, sp_defense=55, speed=45)),
    Pokemon(id=77, name="Ponyta", typing=[Typing.FIRE], base_stats=Stats(hp=50, attack=85, defense=55, sp_attack=65, sp_defense=65, speed=90)),
    Pokemon(id=78, name="Rapidash", typing=[Typing.FIRE], base_stats=Stats(hp=65, attack=100, defense=70, sp_attack=80, sp_defense=80, speed=105)),
    Pokemon(id=79, name="Slowpoke", typing=[Typing.WATER, Typing.PSYCHIC], base_stats=Stats(hp=90, attack=65, defense=65, sp_attack=40, sp_defense=40, speed=15)),
    Pokemon(id=80, name="Slowbro", typing=[Typing.WATER, Typing.PSYCHIC], base_stats=Stats(hp=95, attack=75, defense=110, sp_attack=100, sp_defense=80, speed=30)),
    Pokemon(id=81, name="Magnemite", typing=[Typing.ELECTRIC, Typing.STEEL], base_stats=Stats(hp=25, attack=35, defense=70, sp_attack=95, sp_defense=55, speed=45)),
    Pokemon(id=82, name="Magneton", typing=[Typing.ELECTRIC, Typing.STEEL], base_stats=Stats(hp=50, attack=60, defense=95, sp_attack=120, sp_defense=70, speed=70)),
    Pokemon(id=83, name="Farfetch'd", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=52, attack=90, defense=55, sp_attack=58, sp_defense=62, speed=60)),
    Pokemon(id=84, name="Doduo", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=35, attack=85, defense=45, sp_attack=35, sp_defense=35, speed=75)),
    Pokemon(id=85, name="Dodrio", typing=[Typing.NORMAL, Typing.FLYING], base_stats=Stats(hp=60, attack=110, defense=70, sp_attack=60, sp_defense=60, speed=110)),
    Pokemon(id=86, name="Seel", typing=[Typing.WATER], base_stats=Stats(hp=65, attack=45, defense=55, sp_attack=45, sp_defense=70, speed=45)),
    Pokemon(id=87, name="Dewgong", typing=[Typing.WATER, Typing.ICE], base_stats=Stats(hp=90, attack=70, defense=80, sp_attack=70, sp_defense=95, speed=70)),
    Pokemon(id=88, name="Grimer", typing=[Typing.POISON], base_stats=Stats(hp=80, attack=80, defense=50, sp_attack=40, sp_defense=50, speed=25)),
    Pokemon(id=89, name="Muk", typing=[Typing.POISON], base_stats=Stats(hp=105, attack=105, defense=75, sp_attack=65, sp_defense=100, speed=50)),
    Pokemon(id=90, name="Shellder", typing=[Typing.WATER], base_stats=Stats(hp=30, attack=65, defense=100, sp_attack=45, sp_defense=25, speed=40)),
    Pokemon(id=91, name="Cloyster", typing=[Typing.WATER, Typing.ICE], base_stats=Stats(hp=50, attack=95, defense=180, sp_attack=85, sp_defense=45, speed=70)),
    Pokemon(id=92, name="Gastly", typing=[Typing.GHOST, Typing.POISON], base_stats=Stats(hp=30, attack=35, defense=30, sp_attack=100, sp_defense=35, speed=80)),
    Pokemon(id=93, name="Haunter", typing=[Typing.GHOST, Typing.POISON], base_stats=Stats(hp=45, attack=50, defense=45, sp_attack=115, sp_defense=55, speed=95)),
    Pokemon(id=94, name="Gengar", typing=[Typing.GHOST, Typing.POISON], base_stats=Stats(hp=60, attack=65, defense=60, sp_attack=130, sp_defense=75, speed=110)),
    Pokemon(id=95, name="Onix", typing=[Typing.ROCK, Typing.GROUND], base_stats=Stats(hp=35, attack=45, defense=160, sp_attack=30, sp_defense=45, speed=70)),
    Pokemon(id=96, name="Drowzee", typing=[Typing.PSYCHIC], base_stats=Stats(hp=60, attack=48, defense=45, sp_attack=43, sp_defense=90, speed=42)),
    Pokemon(id=97, name="Hypno", typing=[Typing.PSYCHIC], base_stats=Stats(hp=85, attack=73, defense=70, sp_attack=73, sp_defense=115, speed=67)),
    Pokemon(id=98, name="Krabby", typing=[Typing.WATER], base_stats=Stats(hp=30, attack=105, defense=90, sp_attack=25, sp_defense=25, speed=50)),
    Pokemon(id=99, name="Kingler", typing=[Typing.WATER], base_stats=Stats(hp=55, attack=130, defense=115, sp_attack=50, sp_defense=50, speed=75)),
    Pokemon(id=100, name="Voltorb", typing=[Typing.ELECTRIC], base_stats=Stats(hp=40, attack=30, defense=50, sp_attack=55, sp_defense=55, speed=100)),
    Pokemon(id=101, name="Electrode", typing=[Typing.ELECTRIC], base_stats=Stats(hp=60, attack=50, defense=70, sp_attack=80, sp_defense=80, speed=150)),
    Pokemon(id=102, name="Exeggcute", typing=[Typing.GRASS, Typing.PSYCHIC], base_stats=Stats(hp=60, attack=40, defense=80, sp_attack=60, sp_defense=45, speed=40)),
    Pokemon(id=103, name="Exeggutor", typing=[Typing.GRASS, Typing.PSYCHIC], base_stats=Stats(hp=95, attack=95, defense=85, sp_attack=125, sp_defense=75, speed=55)),
    Pokemon(id=104, name="Cubone", typing=[Typing.GROUND], base_stats=Stats(hp=50, attack=50, defense=95, sp_attack=40, sp_defense=50, speed=35)),
    Pokemon(id=105, name="Marowak", typing=[Typing.GROUND], base_stats=Stats(hp=60, attack=80, defense=110, sp_attack=50, sp_defense=80, speed=45)),
    Pokemon(id=106, name="Hitmonlee", typing=[Typing.FIGHTING], base_stats=Stats(hp=50, attack=120, defense=53, sp_attack=35, sp_defense=110, speed=87)),
    Pokemon(id=107, name="Hitmonchan", typing=[Typing.FIGHTING], base_stats=Stats(hp=50, attack=105, defense=79, sp_attack=35, sp_defense=110, speed=76)),
    Pokemon(id=108, name="Lickitung", typing=[Typing.NORMAL], base_stats=Stats(hp=90, attack=55, defense=75, sp_attack=60, sp_defense=75, speed=30)),
    Pokemon(id=109, name="Koffing", typing=[Typing.POISON], base_stats=Stats(hp=40, attack=65, defense=95, sp_attack=60, sp_defense=45, speed=35)),
    Pokemon(id=110, name="Weezing", typing=[Typing.POISON], base_stats=Stats(hp=65, attack=90, defense=120, sp_attack=85, sp_defense=70, speed=60)),
    Pokemon(id=111, name="Rhyhorn", typing=[Typing.GROUND, Typing.ROCK], base_stats=Stats(hp=80, attack=85, defense=95, sp_attack=30, sp_defense=30, speed=25)),
    Pokemon(id=112, name="Rhydon", typing=[Typing.GROUND, Typing.ROCK], base_stats=Stats(hp=105, attack=130, defense=120, sp_attack=45, sp_defense=45, speed=40)),
    Pokemon(id=113, name="Chansey", typing=[Typing.NORMAL], base_stats=Stats(hp=250, attack=5, defense=5, sp_attack=35, sp_defense=105, speed=50)),
    Pokemon(id=114, name="Tangela", typing=[Typing.GRASS], base_stats=Stats(hp=65, attack=55, defense=115, sp_attack=100, sp_defense=40, speed=60)),
    Pokemon(id=115, name="Kangaskhan", typing=[Typing.NORMAL], base_stats=Stats(hp=105, attack=95, defense=80, sp_attack=40, sp_defense=80, speed=90)),
    Pokemon(id=116, name="Horsea", typing=[Typing.WATER], base_stats=Stats(hp=30, attack=40, defense=70, sp_attack=70, sp_defense=25, speed=60)),
    Pokemon(id=117, name="Seadra", typing=[Typing.WATER], base_stats=Stats(hp=55, attack=65, defense=95, sp_attack=95, sp_defense=45, speed=85)),
    Pokemon(id=118, name="Goldeen", typing=[Typing.WATER], base_stats=Stats(hp=45, attack=67, defense=60, sp_attack=35, sp_defense=50, speed=63)),
    Pokemon(id=119, name="Seaking", typing=[Typing.WATER], base_stats=Stats(hp=80, attack=92, defense=65, sp_attack=65, sp_defense=80, speed=68)),
    Pokemon(id=120, name="Staryu", typing=[Typing.WATER, Typing.PSYCHIC], base_stats=Stats(hp=30, attack=45, defense=55, sp_attack=70, sp_defense=55, speed=85)),
    Pokemon(id=121, name="Starmie", typing=[Typing.WATER, Typing.PSYCHIC], base_stats=Stats(hp=60, attack=75, defense=85, sp_attack=100, sp_defense=85, speed=115)),
    Pokemon(id=122, name="Mr. Mime", typing=[Typing.PSYCHIC, Typing.FAIRY], base_stats=Stats(hp=40, attack=45, defense=65, sp_attack=100, sp_defense=120, speed=90)),
    Pokemon(id=123, name="Scyther", typing=[Typing.BUG, Typing.FLYING], base_stats=Stats(hp=70, attack=110, defense=80, sp_attack=55, sp_defense=80, speed=105)),
    Pokemon(id=124, name="Jynx", typing=[Typing.ICE, Typing.PSYCHIC], base_stats=Stats(hp=65, attack=50, defense=35, sp_attack=115, sp_defense=95, speed=95)),
    Pokemon(id=125, name="Electabuzz", typing=[Typing.ELECTRIC], base_stats=Stats(hp=65, attack=83, defense=57, sp_attack=95, sp_defense=85, speed=105)),
    Pokemon(id=126, name="Magmar", typing=[Typing.FIRE], base_stats=Stats(hp=65, attack=95, defense=57, sp_attack=100, sp_defense=85, speed=93)),
    Pokemon(id=127, name="Pinsir", typing=[Typing.BUG], base_stats=Stats(hp=65, attack=125, defense=100, sp_attack=55, sp_defense=70, speed=85)),
    Pokemon(id=128, name="Tauros", typing=[Typing.NORMAL], base_stats=Stats(hp=75, attack=100, defense=95, sp_attack=40, sp_defense=70, speed=110)),
    Pokemon(id=129, name="Magikarp", typing=[Typing.WATER], base_stats=Stats(hp=20, attack=10, defense=55, sp_attack=15, sp_defense=20, speed=80)),
    Pokemon(id=130, name="Gyarados", typing=[Typing.WATER, Typing.FLYING], base_stats=Stats(hp=95, attack=125, defense=79, sp_attack=60, sp_defense=100, speed=81)),
    Pokemon(id=131, name="Lapras", typing=[Typing.WATER, Typing.ICE], base_stats=Stats(hp=130, attack=85, defense=80, sp_attack=85, sp_defense=95, speed=60)),
    Pokemon(id=132, name="Ditto", typing=[Typing.NORMAL], base_stats=Stats(hp=48, attack=48, defense=48, sp_attack=48, sp_defense=48, speed=48)),
    Pokemon(id=133, name="Eevee", typing=[Typing.NORMAL], base_stats=Stats(hp=55, attack=55, defense=50, sp_attack=45, sp_defense=65, speed=55)),
    Pokemon(id=134, name="Vaporeon", typing=[Typing.WATER], base_stats=Stats(hp=130, attack=65, defense=60, sp_attack=110, sp_defense=95, speed=65)),
    Pokemon(id=135, name="Jolteon", typing=[Typing.ELECTRIC], base_stats=Stats(hp=65, attack=65, defense=60, sp_attack=110, sp_defense=95, speed=130)),
    Pokemon(id=136, name="Flareon", typing=[Typing.FIRE], base_stats=Stats(hp=65, attack=130, defense=60, sp_attack=95, sp_defense=110, speed=65)),
    Pokemon(id=137, name="Porygon", typing=[Typing.NORMAL], base_stats=Stats(hp=65, attack=60, defense=70, sp_attack=85, sp_defense=75, speed=40)),
    Pokemon(id=138, name="Omanyte", typing=[Typing.ROCK, Typing.WATER], base_stats=Stats(hp=35, attack=40, defense=100, sp_attack=90, sp_defense=55, speed=35)),
    Pokemon(id=139, name="Omastar", typing=[Typing.ROCK, Typing.WATER], base_stats=Stats(hp=70, attack=60, defense=125, sp_attack=115, sp_defense=70, speed=55)),
    Pokemon(id=140, name="Kabuto", typing=[Typing.ROCK, Typing.WATER], base_stats=Stats(hp=30, attack=80, defense=90, sp_attack=55, sp_defense=45, speed=55)),
    Pokemon(id=141, name="Kabutops", typing=[Typing.ROCK, Typing.WATER], base_stats=Stats(hp=60, attack=115, defense=105, sp_attack=65, sp_defense=70, speed=80)),
    Pokemon(id=142, name="Aerodactyl", typing=[Typing.ROCK, Typing.FLYING], base_stats=Stats(hp=80, attack=105, defense=65, sp_attack=60, sp_defense=75, speed=130)),
    Pokemon(id=143, name="Snorlax", typing=[Typing.NORMAL], base_stats=Stats(hp=160, attack=110, defense=65, sp_attack=65, sp_defense=110, speed=30)),
    Pokemon(id=144, name="Articuno", typing=[Typing.ICE, Typing.FLYING], base_stats=Stats(hp=90, attack=85, defense=100, sp_attack=95, sp_defense=125, speed=85)),
    Pokemon(id=145, name="Zapdos", typing=[Typing.ELECTRIC, Typing.FLYING], base_stats=Stats(hp=90, attack=90, defense=85, sp_attack=125, sp_defense=90, speed=100)),
    Pokemon(id=146, name="Moltres", typing=[Typing.FIRE, Typing.FLYING], base_stats=Stats(hp=90, attack=100, defense=90, sp_attack=125, sp_defense=85, speed=90)),
    Pokemon(id=147, name="Dratini", typing=[Typing.DRAGON], base_stats=Stats(hp=41, attack=64, defense=45, sp_attack=50, sp_defense=50, speed=50)),
    Pokemon(id=148, name="Dragonair", typing=[Typing.DRAGON], base_stats=Stats(hp=61, attack=84, defense=65, sp_attack=70, sp_defense=70, speed=70)),
    Pokemon(id=149, name="Dragonite", typing=[Typing.DRAGON, Typing.FLYING], base_stats=Stats(hp=91, attack=134, defense=95, sp_attack=100, sp_defense=100, speed=80)),
    Pokemon(id=150, name="Mewtwo", typing=[Typing.PSYCHIC], base_stats=Stats(hp=106, attack=110, defense=90, sp_attack=154, sp_defense=90, speed=130)),
    Pokemon(id=151, name="Mew", typing=[Typing.PSYCHIC], base_stats=Stats(hp=100, attack=100, defense=100, sp_attack=100, sp_defense=100, speed=100)),
]
